#!/usr/bin/env tsx
/**
 * Parses backend/app/enums.py via regex and emits frontend/src/lib/enums.ts.
 *
 * Usage:
 *   tsx scripts/sync-enums.ts          # generate / overwrite
 *   tsx scripts/sync-enums.ts --check  # fail if generated output differs from current file
 */

import * as fs from 'fs'
import * as path from 'path'

// ---------------------------------------------------------------------------
// Paths (relative to the frontend/ directory, which is the script's cwd when
// invoked via npm run sync-enums)
// ---------------------------------------------------------------------------
const SCRIPT_DIR = path.dirname(decodeURIComponent(new URL(import.meta.url).pathname))
const FRONTEND_DIR = path.resolve(SCRIPT_DIR, '..')
const REPO_ROOT = path.resolve(FRONTEND_DIR, '..')
const ENUMS_PY = path.join(REPO_ROOT, 'backend', 'app', 'enums.py')
const OUTPUT_TS = path.join(FRONTEND_DIR, 'src', 'lib', 'enums.ts')

// ---------------------------------------------------------------------------
// Parse
// ---------------------------------------------------------------------------

interface EnumDef {
  name: string
  values: string[]
}

function parseEnums(src: string): EnumDef[] {
  const result: EnumDef[] = []

  // Match each `class FooBar(... Enum ...):` block — capture index of each class start
  const classRe = /^class\s+(\w+)\([^)]*Enum[^)]*\):\s*$/gm
  const classMatches: Array<{ name: string; startIndex: number }> = []
  let classMatch: RegExpExecArray | null

  while ((classMatch = classRe.exec(src)) !== null) {
    classMatches.push({ name: classMatch[1], startIndex: classMatch.index + classMatch[0].length })
  }

  for (let i = 0; i < classMatches.length; i++) {
    const { name, startIndex } = classMatches[i]
    // Slice only until the next class definition (or end of file)
    const endIndex = i + 1 < classMatches.length
      ? classMatches[i + 1].startIndex - classMatches[i + 1].name.length - 10 // conservative
      : src.length

    // Actually, find the preceding `class ` keyword start for the next class
    const nextClassStart = i + 1 < classMatches.length
      ? src.lastIndexOf('\nclass ', classMatches[i + 1].startIndex)
      : src.length

    const block = src.slice(startIndex, nextClassStart > startIndex ? nextClassStart : endIndex)

    // Collect `    MEMBER = "value"` lines within this block
    const memberRe = /^    (\w+)\s*=\s*"([^"]+)"/gm
    const values: string[] = []
    let memberMatch: RegExpExecArray | null
    while ((memberMatch = memberRe.exec(block)) !== null) {
      values.push(memberMatch[2])
    }

    if (values.length > 0) {
      result.push({ name, values })
    }
  }

  return result
}

// ---------------------------------------------------------------------------
// Emit
// ---------------------------------------------------------------------------

/** Returns a reasonable plural form for a TypeScript const array name. */
function pluralize(name: string): string {
  if (name.endsWith('Status')) return name + 'es'
  if (name.endsWith('Type')) return name + 's'
  if (name.endsWith('s')) return name + 'es'
  return name + 's'
}

function enumsToTs(enums: EnumDef[]): string {
  const lines: string[] = [
    '// AUTO-GENERATED by scripts/sync-enums.ts. DO NOT EDIT.',
    '// Source: backend/app/enums.py',
    '//',
    `// Generated at: ${new Date().toISOString()}`,
    '',
  ]

  for (const e of enums) {
    const valuesLiteral = e.values.map((v) => `'${v}'`).join(', ')
    const arrayName = pluralize(e.name) // e.g. UserRoles, CaseStages, ExtractionStatuses
    // Array const
    lines.push(`export const ${arrayName} = [${valuesLiteral}] as const`)
    // Type alias (union of literal types)
    lines.push(`export type ${e.name} = (typeof ${arrayName})[number]`)
    lines.push('')
  }

  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  const checkMode = process.argv.includes('--check')

  if (!fs.existsSync(ENUMS_PY)) {
    console.error(`ERROR: Cannot find ${ENUMS_PY}`)
    process.exit(1)
  }

  const src = fs.readFileSync(ENUMS_PY, 'utf-8')
  const enums = parseEnums(src)

  if (enums.length === 0) {
    console.error('ERROR: No enums found in enums.py — check regex.')
    process.exit(1)
  }

  const totalValues = enums.reduce((acc, e) => acc + e.values.length, 0)
  const generated = enumsToTs(enums)

  if (checkMode) {
    if (!fs.existsSync(OUTPUT_TS)) {
      console.error(`CHECK FAILED: ${OUTPUT_TS} does not exist. Run sync-enums to generate it.`)
      process.exit(1)
    }

    const existing = fs.readFileSync(OUTPUT_TS, 'utf-8')

    // Strip the timestamp line for comparison (it changes every run)
    const normalize = (s: string) =>
      s
        .split('\n')
        .filter((l) => !l.startsWith('// Generated at:'))
        .join('\n')

    if (normalize(existing) !== normalize(generated)) {
      console.error(
        `CHECK FAILED: ${OUTPUT_TS} is out of sync with backend/app/enums.py.\n` +
          `Run: npm run sync-enums`,
      )
      process.exit(1)
    }

    console.log(
      `CHECK PASSED: enums.ts is up to date (${enums.length} enums, ${totalValues} values).`,
    )
    return
  }

  // Ensure output directory exists
  const outDir = path.dirname(OUTPUT_TS)
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true })
  }

  fs.writeFileSync(OUTPUT_TS, generated, 'utf-8')
  console.log(
    `Generated ${OUTPUT_TS}\n` +
      `  ${enums.length} enums: ${enums.map((e) => e.name).join(', ')}\n` +
      `  ${totalValues} total values`,
  )
}

main()
