"""init

Revision ID: 411ef97d3c74
Revises: g1h2i3j4k5l6
Create Date: 2026-04-30 10:41:22.639018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '411ef97d3c74'
down_revision: Union[str, Sequence[str], None] = 'g1h2i3j4k5l6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_negative_area_pincodes_pincode', table_name='negative_area_pincodes')
    op.drop_table('negative_area_pincodes')
    op.drop_index('ix_mrp_catalogue_entries_business_type', table_name='mrp_catalogue_entries')
    op.drop_table('mrp_catalogue_entries')
    op.alter_column('decision_results', 'feature_vector',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=8),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('decision_results', 'feature_vector',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=8),
               existing_nullable=True)
    op.create_table('mrp_catalogue_entries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('business_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('item_canonical', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('item_description', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('mrp_inr', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=32), server_default=sa.text("'AI_ESTIMATED'::character varying"), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('rationale', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('observed_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name='fk_mrp_catalogue_entries_updated_by_user_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_mrp_catalogue_entries'),
    sa.UniqueConstraint('business_type', 'item_canonical', name='uq_mrp_business_type_item')
    )
    op.create_index('ix_mrp_catalogue_entries_business_type', 'mrp_catalogue_entries', ['business_type'], unique=False)
    op.create_table('negative_area_pincodes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pincode', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=64), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name='fk_negative_area_pincodes_uploaded_by_user_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_negative_area_pincodes'),
    sa.UniqueConstraint('pincode', name='uq_negative_area_pincode')
    )
    op.create_index('ix_negative_area_pincodes_pincode', 'negative_area_pincodes', ['pincode'], unique=False)
    # ### end Alembic commands ###
