"""m3 ingestion tables

Revision ID: 81f348677516
Revises: 5c74ea68f52f
Create Date: 2026-04-18 22:15:23.420041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81f348677516'
down_revision: Union[str, Sequence[str], None] = '5c74ea68f52f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dedupe_snapshots',
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_dedupe_snapshots_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dedupe_snapshots')),
    sa.UniqueConstraint('s3_key', name=op.f('uq_dedupe_snapshots_s3_key'))
    )
    op.create_table('checklist_validation_results',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('missing_docs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('present_docs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_checklist_validation_results_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_validation_results'))
    )
    op.create_index(op.f('ix_checklist_validation_results_case_id'), 'checklist_validation_results', ['case_id'], unique=True)
    op.create_table('dedupe_matches',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('match_type', postgresql.ENUM('AADHAAR', 'PAN', 'MOBILE', 'DOB_NAME', name='dedupe_match_type'), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('matched_customer_id', sa.String(length=64), nullable=True),
    sa.Column('matched_details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_dedupe_matches_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['dedupe_snapshots.id'], name=op.f('fk_dedupe_matches_snapshot_id_dedupe_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dedupe_matches'))
    )
    op.create_index(op.f('ix_dedupe_matches_case_id'), 'dedupe_matches', ['case_id'], unique=False)
    op.create_table('case_extractions',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=True),
    sa.Column('extractor_name', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('status', postgresql.ENUM('SUCCESS', 'PARTIAL', 'FAILED', name='extraction_status'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['case_artifacts.id'], name=op.f('fk_case_extractions_artifact_id_case_artifacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_extractions_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_extractions'))
    )
    op.create_index(op.f('ix_case_extractions_case_id'), 'case_extractions', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_extractions_extractor_name'), 'case_extractions', ['extractor_name'], unique=False)
    op.create_index(
        "uq_case_extractions_per_artifact",
        "case_extractions",
        ["case_id", "extractor_name", "artifact_id"],
        unique=True,
        postgresql_where=sa.text("artifact_id IS NOT NULL"),
    )
    op.create_index(
        "uq_case_extractions_aggregate",
        "case_extractions",
        ["case_id", "extractor_name"],
        unique=True,
        postgresql_where=sa.text("artifact_id IS NULL"),
    )
    op.create_index(
        "uq_dedupe_snapshots_active",
        "dedupe_snapshots",
        ["is_active"],
        unique=True,
        postgresql_where=sa.text("is_active = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("uq_dedupe_snapshots_active", table_name="dedupe_snapshots")
    op.drop_index("uq_case_extractions_aggregate", table_name="case_extractions")
    op.drop_index("uq_case_extractions_per_artifact", table_name="case_extractions")
    op.drop_index(op.f('ix_case_extractions_extractor_name'), table_name='case_extractions')
    op.drop_index(op.f('ix_case_extractions_case_id'), table_name='case_extractions')
    op.drop_table('case_extractions')
    op.drop_index(op.f('ix_dedupe_matches_case_id'), table_name='dedupe_matches')
    op.drop_table('dedupe_matches')
    op.drop_index(op.f('ix_checklist_validation_results_case_id'), table_name='checklist_validation_results')
    op.drop_table('checklist_validation_results')
    op.drop_table('dedupe_snapshots')
    sa.Enum(name="dedupe_match_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="extraction_status").drop(op.get_bind(), checkfirst=True)
