"""cases and case_artifacts with enums

Revision ID: b2f148d48781
Revises: 9270485d69ee
Create Date: 2026-04-18 20:55:30.042699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2f148d48781'
down_revision: Union[str, Sequence[str], None] = '9270485d69ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('loan_id', sa.String(length=32), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('zip_s3_key', sa.String(length=512), nullable=False),
    sa.Column('zip_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('current_stage', postgresql.ENUM('UPLOADED', 'CHECKLIST_VALIDATION', 'CHECKLIST_MISSING_DOCS', 'CHECKLIST_VALIDATED', 'INGESTED', 'PHASE_1_DECISIONING', 'PHASE_1_REJECTED', 'PHASE_1_COMPLETE', 'PHASE_2_AUDITING', 'PHASE_2_COMPLETE', 'HUMAN_REVIEW', 'APPROVED', 'REJECTED', 'ESCALATED_TO_CEO', name='case_stage'), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('applicant_name', sa.String(length=255), nullable=True),
    sa.Column('reupload_count', sa.Integer(), nullable=False),
    sa.Column('reupload_allowed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_cases_assigned_to_users')),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_cases_deleted_by_users')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_cases_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases'))
    )
    op.create_index(op.f('ix_cases_current_stage'), 'cases', ['current_stage'], unique=False)
    op.create_index(op.f('ix_cases_loan_id'), 'cases', ['loan_id'], unique=True)
    op.create_index(op.f('ix_cases_uploaded_at'), 'cases', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_cases_uploaded_by'), 'cases', ['uploaded_by'], unique=False)
    op.create_table('case_artifacts',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('artifact_type', postgresql.ENUM('ORIGINAL_ZIP', 'ADDITIONAL_FILE', 'REUPLOAD_ARCHIVE', name='artifact_type'), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_artifacts_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_case_artifacts_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_artifacts')),
    sa.UniqueConstraint('s3_key', name=op.f('uq_case_artifacts_s3_key'))
    )
    op.create_index(op.f('ix_case_artifacts_artifact_type'), 'case_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_case_artifacts_case_id'), 'case_artifacts', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_artifacts_case_id'), table_name='case_artifacts')
    op.drop_index(op.f('ix_case_artifacts_artifact_type'), table_name='case_artifacts')
    op.drop_table('case_artifacts')
    op.drop_index(op.f('ix_cases_uploaded_by'), table_name='cases')
    op.drop_index(op.f('ix_cases_uploaded_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_loan_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_current_stage'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
    # Drop the Postgres enum types (append-only enums need explicit cleanup)
    sa.Enum(name="artifact_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="case_stage").drop(op.get_bind(), checkfirst=True)
