"""m5_decisioning_tables

Revision ID: b47f40f5fbcc
Revises: 81f348677516
Create Date: 2026-04-21 01:49:38.077155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

try:
    from pgvector.sqlalchemy import Vector as VectorType  # type: ignore[import]
except ImportError:  # pragma: no cover
    VectorType = None  # type: ignore[assignment,misc]

# revision identifiers, used by Alembic.
revision: str = 'b47f40f5fbcc'
down_revision: Union[str, Sequence[str], None] = '81f348677516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _vector_extension_available(conn) -> bool:
    """Return True if the vector Postgres extension can be created."""
    conn.execute(sa.text("SAVEPOINT probe_vector"))
    try:
        conn.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
        conn.execute(sa.text("RELEASE SAVEPOINT probe_vector"))
        return True
    except Exception:  # noqa: BLE001
        conn.execute(sa.text("ROLLBACK TO SAVEPOINT probe_vector"))
        conn.execute(sa.text("RELEASE SAVEPOINT probe_vector"))
        return False


def upgrade() -> None:
    """Upgrade schema."""
    # Enable extensions required for M5 decisioning.
    # pgvector may not be installed in all environments (e.g. local dev postgres).
    # pg_trgm is standard Postgres contrib.
    conn = op.get_bind()
    vector_available = _vector_extension_available(conn)
    conn.execute(sa.text("CREATE EXTENSION IF NOT EXISTS pg_trgm"))

    # Choose the column type based on whether pgvector is available
    if vector_available and VectorType is not None:
        feature_vector_col = sa.Column('feature_vector', VectorType(8), nullable=True)
    else:
        feature_vector_col = sa.Column(
            'feature_vector',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mrp_entries',
    sa.Column('item_normalized_name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('unit_price_inr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source', postgresql.ENUM('MANUAL', 'WEB_KNOWLEDGE', 'OPUS_ESTIMATE', name='mrp_source'), nullable=False),
    sa.Column('source_case_id', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mrp_entries')),
    sa.UniqueConstraint('item_normalized_name', name='uq_mrp_entries_name')
    )
    op.create_index(op.f('ix_mrp_entries_item_normalized_name'), 'mrp_entries', ['item_normalized_name'], unique=False)
    op.create_table('decision_results',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('phase', sa.String(length=8), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='decision_status'), nullable=False),
    sa.Column('final_decision', postgresql.ENUM('APPROVE', 'APPROVE_WITH_CONDITIONS', 'REJECT', 'ESCALATE_TO_CEO', name='decision_outcome'), nullable=True),
    sa.Column('recommended_amount', sa.Integer(), nullable=True),
    sa.Column('recommended_tenure', sa.Integer(), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reasoning_markdown', sa.Text(), nullable=True),
    sa.Column('pros_cons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deviations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.SmallInteger(), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    feature_vector_col,
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_decision_results_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name=op.f('fk_decision_results_triggered_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_results'))
    )
    op.create_index(op.f('ix_decision_results_case_id'), 'decision_results', ['case_id'], unique=False)
    op.create_index('ix_decision_results_case_id_created', 'decision_results', ['case_id', 'created_at'], unique=False)
    op.create_table('decision_steps',
    sa.Column('decision_result_id', sa.Uuid(), nullable=False),
    sa.Column('step_number', sa.SmallInteger(), nullable=False),
    sa.Column('step_name', sa.String(length=64), nullable=False),
    sa.Column('model_used', sa.String(length=64), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='step_status'), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_result_id'], ['decision_results.id'], name=op.f('fk_decision_steps_decision_result_id_decision_results'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_steps')),
    sa.UniqueConstraint('decision_result_id', 'step_number', name='uq_decision_steps_result_step')
    )
    op.create_index(op.f('ix_decision_steps_decision_result_id'), 'decision_steps', ['decision_result_id'], unique=False)
    op.drop_index(op.f('uq_dedupe_snapshots_active'), table_name='dedupe_snapshots', postgresql_where='(is_active = true)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_dedupe_snapshots_active'), 'dedupe_snapshots', ['is_active'], unique=True, postgresql_where='(is_active = true)')
    op.drop_index(op.f('ix_decision_steps_decision_result_id'), table_name='decision_steps')
    op.drop_table('decision_steps')
    op.drop_index('ix_decision_results_case_id_created', table_name='decision_results')
    op.drop_index(op.f('ix_decision_results_case_id'), table_name='decision_results')
    op.drop_table('decision_results')
    op.drop_index(op.f('ix_mrp_entries_item_normalized_name'), table_name='mrp_entries')
    op.drop_table('mrp_entries')
    # ### end Alembic commands ###
