// AUTO-GENERATED by scripts/sync-enums.ts. DO NOT EDIT.
// Source: backend/app/enums.py
//
// Generated at: 2026-04-25T12:39:46.240Z

export const UserRoles = ['user', 'admin', 'ceo', 'credit_ho', 'ai_analyser', 'underwriter'] as const
export type UserRole = (typeof UserRoles)[number]

export const CaseStages = ['UPLOADED', 'CHECKLIST_VALIDATION', 'CHECKLIST_MISSING_DOCS', 'CHECKLIST_VALIDATED', 'INGESTED', 'PHASE_1_DECISIONING', 'PHASE_1_REJECTED', 'PHASE_1_COMPLETE', 'PHASE_2_AUDITING', 'PHASE_2_COMPLETE', 'HUMAN_REVIEW', 'APPROVED', 'REJECTED', 'ESCALATED_TO_CEO'] as const
export type CaseStage = (typeof CaseStages)[number]

export const ArtifactTypes = ['ORIGINAL_ZIP', 'ADDITIONAL_FILE', 'REUPLOAD_ARCHIVE'] as const
export type ArtifactType = (typeof ArtifactTypes)[number]

export const ArtifactSubtypes = ['KYC_AADHAAR', 'KYC_PAN', 'KYC_VOTER', 'KYC_DL', 'KYC_PASSPORT', 'RATION_CARD', 'ELECTRICITY_BILL', 'BANK_ACCOUNT_PROOF', 'INCOME_PROOF', 'CO_APPLICANT_AADHAAR', 'CO_APPLICANT_PAN', 'AUTO_CAM', 'CHECKLIST', 'PD_SHEET', 'EQUIFAX_HTML', 'CIBIL_HTML', 'HIGHMARK_HTML', 'EXPERIAN_HTML', 'BANK_STATEMENT', 'HOUSE_VISIT_PHOTO', 'BUSINESS_PREMISES_PHOTO', 'KYC_VIDEO', 'LOAN_AGREEMENT', 'DPN', 'LAPP', 'LAGR', 'NACH', 'KFS', 'UDYAM_REG', 'UNKNOWN', 'DEDUPE_REPORT', 'TVR_AUDIO'] as const
export type ArtifactSubtype = (typeof ArtifactSubtypes)[number]

export const ExtractionStatuses = ['SUCCESS', 'PARTIAL', 'FAILED'] as const
export type ExtractionStatus = (typeof ExtractionStatuses)[number]

export const DedupeMatchTypes = ['AADHAAR', 'PAN', 'MOBILE', 'DOB_NAME'] as const
export type DedupeMatchType = (typeof DedupeMatchTypes)[number]

export const DecisionStatuses = ['PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED'] as const
export type DecisionStatus = (typeof DecisionStatuses)[number]

export const DecisionOutcomes = ['APPROVE', 'APPROVE_WITH_CONDITIONS', 'REJECT', 'ESCALATE_TO_CEO'] as const
export type DecisionOutcome = (typeof DecisionOutcomes)[number]

export const StepStatuses = ['PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED'] as const
export type StepStatus = (typeof StepStatuses)[number]

export const MrpSources = ['MANUAL', 'WEB_KNOWLEDGE', 'OPUS_ESTIMATE'] as const
export type MrpSource = (typeof MrpSources)[number]

export const FeedbackVerdicts = ['APPROVE', 'NEEDS_REVISION', 'REJECT'] as const
export type FeedbackVerdict = (typeof FeedbackVerdicts)[number]

export const VerificationLevelNumbers = ['L1_ADDRESS', 'L1_5_CREDIT', 'L2_BANKING', 'L3_VISION', 'L4_AGREEMENT', 'L5_SCORING', 'L5_5_DEDUPE_TVR'] as const
export type VerificationLevelNumber = (typeof VerificationLevelNumbers)[number]

export const VerificationLevelStatuses = ['PENDING', 'RUNNING', 'PASSED', 'PASSED_WITH_MD_OVERRIDE', 'BLOCKED', 'FAILED'] as const
export type VerificationLevelStatus = (typeof VerificationLevelStatuses)[number]

export const LevelIssueStatuses = ['OPEN', 'ASSESSOR_RESOLVED', 'MD_APPROVED', 'MD_REJECTED'] as const
export type LevelIssueStatus = (typeof LevelIssueStatuses)[number]

export const LevelIssueSeveritys = ['INFO', 'WARNING', 'CRITICAL'] as const
export type LevelIssueSeverity = (typeof LevelIssueSeveritys)[number]

export const DocTypes = ['AADHAAR', 'PAN', 'RATION', 'ELECTRICITY_BILL'] as const
export type DocType = (typeof DocTypes)[number]

export const Partys = ['APPLICANT', 'CO_APPLICANT'] as const
export type Party = (typeof Partys)[number]
