/**
 * Zod parsers + inferred TypeScript types mirroring backend Pydantic schemas.
 *
 * Reference: backend/app/schemas/*.py
 * Generated by: M4 scaffolding (T9)
 */

import { z } from 'zod'

// ---------------------------------------------------------------------------
// Primitives
// ---------------------------------------------------------------------------

const uuid = z.string().uuid()
const isoDatetime = z.string().datetime({ offset: true })

// ---------------------------------------------------------------------------
// Auth schemas  (backend/app/schemas/auth.py)
// ---------------------------------------------------------------------------

export const LoginResponseSchema = z.object({
  access_token: z.string(),
  refresh_token: z.string(),
  token_type: z.string().default('bearer'),
  mfa_required: z.boolean().default(false),
  mfa_enrollment_required: z.boolean().default(false),
})
export type LoginResponse = z.infer<typeof LoginResponseSchema>

export const MFAEnrollResponseSchema = z.object({
  secret: z.string(),
  otpauth_uri: z.string(),
})
export type MFAEnrollResponse = z.infer<typeof MFAEnrollResponseSchema>

export const MFAVerifyRequestSchema = z.object({
  code: z.string().regex(/^\d{6}$/),
})
export type MFAVerifyRequest = z.infer<typeof MFAVerifyRequestSchema>

// ---------------------------------------------------------------------------
// User schemas  (backend/app/schemas/user.py)
// ---------------------------------------------------------------------------

export const UserReadSchema = z.object({
  id: uuid,
  email: z.string().email(),
  full_name: z.string(),
  role: z.string(), // UserRole — kept loose to avoid import cycle; narrow at use-site
  mfa_enabled: z.boolean(),
  is_active: z.boolean(),
  last_login_at: isoDatetime.nullable(),
  created_at: isoDatetime,
})
export type UserRead = z.infer<typeof UserReadSchema>

// ---------------------------------------------------------------------------
// Case artifact schemas  (backend/app/schemas/case.py)
// ---------------------------------------------------------------------------

export const CaseArtifactReadSchema = z.object({
  id: uuid,
  filename: z.string(),
  artifact_type: z.string(), // ArtifactType
  size_bytes: z.number().int().nullable(),
  content_type: z.string().nullable(),
  uploaded_at: isoDatetime,
  download_url: z.string().nullable().optional(),
  attachment_url: z.string().nullable().optional(),
  subtype: z.string().nullable().optional(),
})
export type CaseArtifactRead = z.infer<typeof CaseArtifactReadSchema>

// ---------------------------------------------------------------------------
// Case schemas  (backend/app/schemas/case.py)
// ---------------------------------------------------------------------------

export const CaseReadSchema = z.object({
  id: uuid,
  loan_id: z.string(),
  applicant_name: z.string().nullable(),
  uploaded_by: uuid,
  uploaded_at: isoDatetime,
  finalized_at: isoDatetime.nullable(),
  current_stage: z.string(), // CaseStage
  assigned_to: uuid.nullable(),
  reupload_count: z.number().int(),
  reupload_allowed_until: isoDatetime.nullable(),
  is_deleted: z.boolean(),
  created_at: isoDatetime,
  updated_at: isoDatetime,
  artifacts: z.array(CaseArtifactReadSchema).default([]),
  // M4: wizard-captured fields
  loan_amount: z.number().int().nullable().optional(),
  loan_tenure_months: z.number().int().nullable().optional(),
  co_applicant_name: z.string().nullable().optional(),
  occupation: z.string().nullable().optional(),
  // Two-step deletion-approval flow — populated when a non-MD user has
  // requested deletion and the MD hasn't acted yet. Cleared on
  // approve (case becomes is_deleted=true) or reject (back to clean).
  deletion_requested_at: isoDatetime.nullable().optional(),
  deletion_requested_by: uuid.nullable().optional(),
  deletion_reason: z.string().nullable().optional(),
  // Count of unresolved LevelIssues (OPEN + ASSESSOR_RESOLVED). Drives
  // the stage badge: non-zero → red override; zero → stage-native colour.
  open_issue_count: z.number().int().nullable().optional(),
})
export type CaseRead = z.infer<typeof CaseReadSchema>

export const CaseListResponseSchema = z.object({
  cases: z.array(CaseReadSchema),
  total: z.number().int(),
  limit: z.number().int(),
  offset: z.number().int(),
})
export type CaseListResponse = z.infer<typeof CaseListResponseSchema>

export const CaseInitiateRequestSchema = z.object({
  loan_id: z.string().regex(/^[A-Za-z0-9-]{3,32}$/),
  applicant_name: z.string().max(255).nullable().optional(),
  loan_amount: z.number().int().nullable().optional(),
  loan_tenure_months: z.number().int().nullable().optional(),
  co_applicant_name: z.string().max(255).nullable().optional(),
  occupation: z.string().max(255).nullable().optional(),
})
export type CaseInitiateRequest = z.infer<typeof CaseInitiateRequestSchema>

export const CaseInitiateResponseSchema = z.object({
  case_id: uuid,
  upload_url: z.string().url(),
  upload_fields: z.record(z.string()),
  upload_key: z.string(),
  expires_at: isoDatetime,
  reupload: z.boolean().default(false),
})
export type CaseInitiateResponse = z.infer<typeof CaseInitiateResponseSchema>

// ---------------------------------------------------------------------------
// Extraction schemas  (backend/app/schemas/extraction.py)
// ---------------------------------------------------------------------------

export const CaseExtractionReadSchema = z.object({
  id: uuid,
  case_id: uuid,
  artifact_id: uuid.nullable(),
  extractor_name: z.string(),
  schema_version: z.string(),
  status: z.string(), // ExtractionStatus
  data: z.record(z.unknown()),
  warnings: z.array(z.string()).nullable(),
  error_message: z.string().nullable(),
  extracted_at: isoDatetime,
  created_at: isoDatetime,
})
export type CaseExtractionRead = z.infer<typeof CaseExtractionReadSchema>

export const ChecklistValidationResultReadSchema = z.object({
  id: uuid,
  case_id: uuid,
  is_complete: z.boolean(),
  missing_docs: z.array(z.record(z.unknown())),
  present_docs: z.array(z.record(z.unknown())),
  validated_at: isoDatetime,
})
export type ChecklistValidationResultRead = z.infer<typeof ChecklistValidationResultReadSchema>

export const DedupeMatchReadSchema = z.object({
  id: uuid,
  case_id: uuid,
  snapshot_id: uuid,
  match_type: z.string(), // DedupeMatchType
  match_score: z.number(),
  matched_customer_id: z.string().nullable(),
  matched_details_json: z.record(z.unknown()),
  created_at: isoDatetime,
})
export type DedupeMatchRead = z.infer<typeof DedupeMatchReadSchema>

// ---------------------------------------------------------------------------
// Dedupe snapshot schemas  (backend/app/schemas/dedupe_snapshot.py)
// ---------------------------------------------------------------------------

export const DedupeSnapshotReadSchema = z.object({
  id: uuid,
  uploaded_by: uuid,
  uploaded_at: isoDatetime,
  row_count: z.number().int(),
  is_active: z.boolean(),
  download_url: z.string().nullable().optional(),
})
export type DedupeSnapshotRead = z.infer<typeof DedupeSnapshotReadSchema>

// ---------------------------------------------------------------------------
// Audit log schemas  (backend/app/schemas/audit.py)
// ---------------------------------------------------------------------------

export const AuditLogReadSchema = z.object({
  id: uuid,
  actor_user_id: uuid.nullable(),
  action: z.string(),
  entity_type: z.string(),
  entity_id: z.string().nullable(),
  before_json: z.record(z.unknown()).nullable(),
  after_json: z.record(z.unknown()).nullable(),
  ip_address: z.string().nullable(),
  user_agent: z.string().nullable(),
  created_at: isoDatetime,
})
export type AuditLogRead = z.infer<typeof AuditLogReadSchema>

// ---------------------------------------------------------------------------
// Feedback schemas  (backend/app/schemas/feedback.py)  M4
// ---------------------------------------------------------------------------

export const FeedbackCreateSchema = z.object({
  verdict: z.enum(['APPROVE', 'NEEDS_REVISION', 'REJECT']),
  notes: z.string().max(4000).nullable().optional(),
  phase: z.string().max(32).optional(),
})
export type FeedbackCreate = z.infer<typeof FeedbackCreateSchema>

export const FeedbackReadSchema = z.object({
  id: uuid,
  case_id: uuid,
  actor_user_id: uuid,
  verdict: z.enum(['APPROVE', 'NEEDS_REVISION', 'REJECT']),
  notes: z.string().nullable(),
  phase: z.string(),
  created_at: isoDatetime,
})
export type FeedbackRead = z.infer<typeof FeedbackReadSchema>

// ---------------------------------------------------------------------------
// Decisioning schemas  (backend/app/schemas/decision.py)  M5
// ---------------------------------------------------------------------------

export const DecisionStepReadSchema = z.object({
  id: uuid,
  decision_result_id: uuid,
  step_number: z.number().int(),
  step_name: z.string(),
  model_used: z.string().nullable(),
  status: z.string(), // StepStatus
  input_tokens: z.number().int().nullable(),
  output_tokens: z.number().int().nullable(),
  cache_read_tokens: z.number().int().nullable(),
  cache_creation_tokens: z.number().int().nullable(),
  cost_usd: z.string().nullable(), // Decimal serialized as string
  output_data: z.record(z.unknown()).nullable(),
  citations: z.unknown().nullable(),
  error_message: z.string().nullable(),
  started_at: isoDatetime.nullable(),
  completed_at: isoDatetime.nullable(),
  created_at: isoDatetime,
  updated_at: isoDatetime,
})
export type DecisionStepRead = z.infer<typeof DecisionStepReadSchema>

export const DecisionResultReadSchema = z.object({
  id: uuid,
  case_id: uuid,
  phase: z.string(),
  status: z.string(), // DecisionStatus
  final_decision: z.string().nullable(), // DecisionOutcome | null
  recommended_amount: z.number().int().nullable(),
  recommended_tenure: z.number().int().nullable(),
  conditions: z.unknown().nullable(),
  reasoning_markdown: z.string().nullable(),
  pros_cons: z.unknown().nullable(),
  deviations: z.unknown().nullable(),
  risk_summary: z.unknown().nullable(),
  confidence_score: z.number().int().nullable(),
  token_usage: z.record(z.unknown()).nullable(),
  total_cost_usd: z.string().nullable(), // Decimal serialized as string
  error_message: z.string().nullable(),
  triggered_by: uuid.nullable(),
  started_at: isoDatetime.nullable(),
  completed_at: isoDatetime.nullable(),
  created_at: isoDatetime,
  updated_at: isoDatetime,
})
export type DecisionResultRead = z.infer<typeof DecisionResultReadSchema>

// ---------------------------------------------------------------------------
// Verification schemas  (backend/app/schemas/verification.py)  4-level gate
// ---------------------------------------------------------------------------

export const VerificationLevelNumberSchema = z.enum([
  'L1_ADDRESS',
  'L1_5_CREDIT',
  'L2_BANKING',
  'L3_VISION',
  'L4_AGREEMENT',
  'L5_SCORING',
  'L5_5_DEDUPE_TVR',
])
export type VerificationLevelNumber = z.infer<typeof VerificationLevelNumberSchema>

export const VerificationLevelStatusSchema = z.enum([
  'PENDING',
  'RUNNING',
  'PASSED',
  'PASSED_WITH_MD_OVERRIDE',
  'BLOCKED',
  'FAILED',
])
export type VerificationLevelStatus = z.infer<typeof VerificationLevelStatusSchema>

export const LevelIssueStatusSchema = z.enum([
  'OPEN',
  'ASSESSOR_RESOLVED',
  'MD_APPROVED',
  'MD_REJECTED',
])
export type LevelIssueStatus = z.infer<typeof LevelIssueStatusSchema>

export const LevelIssueSeveritySchema = z.enum(['INFO', 'WARNING', 'CRITICAL'])
export type LevelIssueSeverity = z.infer<typeof LevelIssueSeveritySchema>

export const VerificationResultReadSchema = z.object({
  id: uuid,
  case_id: uuid,
  level_number: VerificationLevelNumberSchema,
  status: VerificationLevelStatusSchema,
  sub_step_results: z.record(z.unknown()).nullable().optional(),
  md_override_records: z.record(z.unknown()).nullable().optional(),
  cost_usd: z.string().nullable(),
  error_message: z.string().nullable(),
  triggered_by: uuid.nullable(),
  started_at: isoDatetime.nullable(),
  completed_at: isoDatetime.nullable(),
  created_at: isoDatetime,
})
export type VerificationResultRead = z.infer<typeof VerificationResultReadSchema>

export const L1ExtractedDocumentReadSchema = z.object({
  id: uuid,
  case_id: uuid,
  artifact_id: uuid.nullable(),
  doc_type: z.enum(['AADHAAR', 'PAN', 'RATION', 'ELECTRICITY_BILL']),
  party: z.enum(['APPLICANT', 'CO_APPLICANT']),
  extracted_name: z.string().nullable(),
  extracted_father_name: z.string().nullable(),
  extracted_address: z.string().nullable(),
  extracted_number: z.string().nullable(),
  extracted_dob: z.string().nullable(),
  extracted_gender: z.string().nullable(),
  model_used: z.string().nullable(),
  cost_usd: z.string().nullable(),
  error_message: z.string().nullable(),
  created_at: isoDatetime,
})
export type L1ExtractedDocumentRead = z.infer<typeof L1ExtractedDocumentReadSchema>

export const LevelIssueReadSchema = z.object({
  id: uuid,
  verification_result_id: uuid,
  sub_step_id: z.string(),
  severity: LevelIssueSeveritySchema,
  description: z.string(),
  evidence: z.record(z.unknown()).nullable(),
  status: LevelIssueStatusSchema,
  assessor_user_id: uuid.nullable(),
  assessor_note: z.string().nullable(),
  assessor_resolved_at: isoDatetime.nullable(),
  md_user_id: uuid.nullable(),
  md_rationale: z.string().nullable(),
  md_reviewed_at: isoDatetime.nullable(),
  artifact_id: uuid.nullable(),
  created_at: isoDatetime,
  updated_at: isoDatetime,
})
export type LevelIssueRead = z.infer<typeof LevelIssueReadSchema>

export const VerificationOverviewSchema = z.object({
  case_id: uuid,
  levels: z.array(VerificationResultReadSchema),
  gate_open_for_phase_1: z.boolean(),
  open_issue_count: z.number().int().default(0),
  awaiting_md_count: z.number().int().default(0),
  md_approved_count: z.number().int().default(0),
  md_rejected_count: z.number().int().default(0),
})
export type VerificationOverview = z.infer<typeof VerificationOverviewSchema>

export const VerificationLevelDetailSchema = z.object({
  result: VerificationResultReadSchema,
  extracted_documents: z.array(L1ExtractedDocumentReadSchema),
  issues: z.array(LevelIssueReadSchema),
})
export type VerificationLevelDetail = z.infer<typeof VerificationLevelDetailSchema>

export const TriggerLevelResponseSchema = z.object({
  verification_result_id: uuid,
  case_id: uuid,
  level_number: VerificationLevelNumberSchema,
  status: VerificationLevelStatusSchema,
})
export type TriggerLevelResponse = z.infer<typeof TriggerLevelResponseSchema>

// ---------------------------------------------------------------------------
// MD Approvals queue — cross-case feed of unresolved issues
// ---------------------------------------------------------------------------

export const MDQueueItemSchema = z.object({
  issue: LevelIssueReadSchema,
  case_id: uuid,
  loan_id: z.string(),
  applicant_name: z.string().nullable(),
  co_applicant_name: z.string().nullable(),
  loan_amount: z.number().nullable(),
  level_number: VerificationLevelNumberSchema,
  level_status: VerificationLevelStatusSchema,
  level_completed_at: isoDatetime.nullable(),
})
export type MDQueueItem = z.infer<typeof MDQueueItemSchema>

export const MDQueueResponseSchema = z.object({
  items: z.array(MDQueueItemSchema),
  total_open: z.number().int(),
  total_awaiting_md: z.number().int(),
})
export type MDQueueResponse = z.infer<typeof MDQueueResponseSchema>

// ---------------------------------------------------------------------------
// Photos + precedents
// ---------------------------------------------------------------------------

export const CasePhotoItemSchema = z.object({
  artifact_id: uuid,
  filename: z.string(),
  subtype: z.string(),
  download_url: z.string(),
})
export type CasePhotoItem = z.infer<typeof CasePhotoItemSchema>

export const CasePhotosResponseSchema = z.object({
  case_id: uuid,
  subtype: z.string(),
  items: z.array(CasePhotoItemSchema),
})
export type CasePhotosResponse = z.infer<typeof CasePhotosResponseSchema>

export const PrecedentItemSchema = z.object({
  issue_id: uuid,
  case_id: uuid,
  loan_id: z.string(),
  applicant_name: z.string().nullable(),
  sub_step_id: z.string(),
  severity: z.string(),
  decision: z.string(),
  md_rationale: z.string().nullable(),
  md_reviewed_at: isoDatetime.nullable(),
})
export type PrecedentItem = z.infer<typeof PrecedentItemSchema>

export const PrecedentsResponseSchema = z.object({
  sub_step_id: z.string(),
  items: z.array(PrecedentItemSchema),
  approved_count: z.number().int(),
  rejected_count: z.number().int(),
})
export type PrecedentsResponse = z.infer<typeof PrecedentsResponseSchema>

// L3 visual-evidence additions (Part A) — live under
// VerificationResult.sub_step_results. Consumed by the new L3
// header panel + click-to-expand pass cards.
export type L3VisualEvidencePhoto = {
  artifact_id: string
  filename: string
  subtype: string
}

export type L3VisualEvidence = {
  house_photos: L3VisualEvidencePhoto[]
  business_photos: L3VisualEvidencePhoto[]
  house_photos_evaluated: number
  business_photos_evaluated: number
}

export type L3StockAnalysis = {
  business_type: string | null
  business_subtype: string | null
  loan_amount_inr: number | null
  stock_value_estimate_inr: number | null
  visible_equipment_value_inr: number | null
  visible_collateral_inr: number | null
  cattle_count: number | null
  cattle_health: string | null
  stock_condition: string | null
  stock_variety: string | null
  coverage_pct: number | null
  floor_pct_critical: number | null
  floor_pct_warning: number | null
  recommended_loan_amount_inr: number | null
  recommended_loan_rationale: string | null
  cut_pct: number | null
  reasoning: string
}

// pass_evidence is keyed by sub_step_id; values are loosely typed
// because each rule's shape differs. The L3 pass cards narrow on
// sub_step_id at render time. Other levels add keys in Part B.
export type L3PassEvidence = Record<string, Record<string, unknown>>

// ---------------------------------------------------------------------------
// MRP Catalogue  (backend/app/schemas/mrp_catalogue.py)
// ---------------------------------------------------------------------------

export const MrpEntrySchema = z.object({
  id: z.string(),
  business_type: z.string(),
  item_canonical: z.string(),
  item_description: z.string(),
  category: z.enum(['equipment', 'stock', 'consumable', 'other']),
  mrp_inr: z.number().int(),
  source: z.enum(['AI_ESTIMATED', 'MANUAL', 'OVERRIDDEN_FROM_AI']),
  confidence: z.enum(['high', 'medium', 'low']).nullable(),
  rationale: z.string().nullable(),
  observed_count: z.number().int(),
  updated_at: z.string(),
  updated_by_user_id: z.string().nullable(),
})
export type MrpEntry = z.infer<typeof MrpEntrySchema>

// ---------------------------------------------------------------------------
// CAM discrepancy engine  (backend/app/schemas/cam_discrepancy.py)
// ---------------------------------------------------------------------------

export const DiscrepancySeveritySchema = z.enum(['CRITICAL', 'WARNING'])
export type DiscrepancySeverity = z.infer<typeof DiscrepancySeveritySchema>

export const DiscrepancyResolutionKindSchema = z.enum([
  'CORRECTED_CM_IL',
  'SYSTEMCAM_EDIT_REQUESTED',
  'JUSTIFIED',
])
export type DiscrepancyResolutionKind = z.infer<typeof DiscrepancyResolutionKindSchema>

export const SystemCamEditRequestStatusSchema = z.enum([
  'PENDING',
  'APPROVED',
  'REJECTED',
  'WITHDRAWN',
])
export type SystemCamEditRequestStatus = z.infer<typeof SystemCamEditRequestStatusSchema>

export const CamDiscrepancyFlagSchema = z.object({
  field_key: z.string(),
  field_label: z.string(),
  system_cam_value: z.string().nullable(),
  cm_cam_il_value: z.string().nullable(),
  diff_abs: z.number().nullable().optional(),
  diff_pct: z.number().nullable().optional(),
  severity: DiscrepancySeveritySchema,
  tolerance_description: z.string(),
  note: z.string().default(''),
})
export type CamDiscrepancyFlag = z.infer<typeof CamDiscrepancyFlagSchema>

export const CamDiscrepancyResolutionReadSchema = z.object({
  id: uuid,
  case_id: uuid,
  field_key: z.string(),
  field_label: z.string(),
  system_cam_value_at_resolve: z.string().nullable(),
  cm_cam_il_value_at_resolve: z.string().nullable(),
  severity_at_resolve: DiscrepancySeveritySchema,
  kind: DiscrepancyResolutionKindSchema,
  corrected_value: z.string().nullable(),
  comment: z.string(),
  resolved_by: uuid,
  resolved_at: isoDatetime,
  created_at: isoDatetime,
})
export type CamDiscrepancyResolutionRead = z.infer<typeof CamDiscrepancyResolutionReadSchema>

export const CamDiscrepancyResolveRequestSchema = z.object({
  kind: DiscrepancyResolutionKindSchema,
  comment: z.string().min(10).max(4000),
  corrected_value: z.string().max(500).nullable().optional(),
})
export type CamDiscrepancyResolveRequest = z.infer<typeof CamDiscrepancyResolveRequestSchema>

export const SystemCamEditRequestReadSchema = z.object({
  id: uuid,
  case_id: uuid,
  resolution_id: uuid.nullable(),
  field_key: z.string(),
  field_label: z.string(),
  current_system_cam_value: z.string().nullable(),
  requested_system_cam_value: z.string(),
  justification: z.string(),
  status: SystemCamEditRequestStatusSchema,
  requested_by: uuid,
  requested_at: isoDatetime,
  decided_by: uuid.nullable(),
  decided_at: isoDatetime.nullable(),
  decision_comment: z.string().nullable(),
  created_at: isoDatetime,
})
export type SystemCamEditRequestRead = z.infer<typeof SystemCamEditRequestReadSchema>

export const SystemCamEditDecisionRequestSchema = z.object({
  approve: z.boolean(),
  decision_comment: z.string().min(10).max(4000),
})
export type SystemCamEditDecisionRequest = z.infer<typeof SystemCamEditDecisionRequestSchema>

export const CamDiscrepancyViewSchema = z.object({
  field_key: z.string(),
  field_label: z.string(),
  flag: CamDiscrepancyFlagSchema.nullable().optional(),
  resolution: CamDiscrepancyResolutionReadSchema.nullable().optional(),
  pending_edit_request: SystemCamEditRequestReadSchema.nullable().optional(),
})
export type CamDiscrepancyView = z.infer<typeof CamDiscrepancyViewSchema>

export const CamDiscrepancySummarySchema = z.object({
  case_id: uuid,
  generated_at: isoDatetime,
  total: z.number().int(),
  unresolved_critical: z.number().int(),
  unresolved_warning: z.number().int(),
  phase1_blocked: z.boolean(),
  views: z.array(CamDiscrepancyViewSchema),
})
export type CamDiscrepancySummary = z.infer<typeof CamDiscrepancySummarySchema>
